package org.trad.pcl.Helpers;

public enum OperatorEnum {

    NOT, EQUALS, NOT_EQUALS, LESS_THAN, GREATER_THAN, LESS_THAN_OR_EQUAL, GREATER_THAN_OR_EQUAL, ADD, SUB, MULTIPLY, DIVIDE, MODULO, AND, ANDTHEN, OR, ORELSE
}
